[package]
name = "fibber"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Gautham Ramanarayanan"]
license = "MIT"
description = "A CeTZ package for creating microfabrication process diagrams in typst."
repository = ""
keywords = ["diagram","microfabrication","fabrication"]
categories = [""]
exclude = ["examples"]
compiler = "0.13.1"
